### ISSUE TITLE
masi 2.0 - new page error

### ISSUE THREAD

**Issue by Hobokens** [b13/masi#30]
With TYPO3 10.4.33 and masi 2.0 I get the following error when adding a page to the pagetree:

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to undefined method Doctrine\DBAL\Driver\Mysqli\MysqliStatement::fetchAssociative() | Error thrown in file /var/www/vhosts/xxxx.my-provider.de/httpdocs/typo3cms/hfmw/typo3conf/ext/masi/Classes/SlugModifier.php in line 86. Requested URL: https://www.my-domain.de/typo3/index.php?route=%%2Frecord%%2Fedit&token=--AnonymizedToken--&edit%%5Bpages%%5D%%5B672%%5D=new&returnUrl=%%2Ftypo3%%2Findex.php%%3Froute%%3D%%252Fmodule%%252Fweb%%252Flist%%26token%%3Dc70180522950b01a95c7a57fe6962741b0bc2a21%%26id%%3D672%%26table%%3D%%26imagemode%%3D1`

**Comment by achimfritz** [comment]
@Hobokens 
do you use non-composer mode?

**Comment by Hobokens** [comment]
@achimfritz 
Yes,  I loaded masi from TER.
