### ISSUE TITLE
The field 'exclude_slug_for_subpages' doesn't appear on folder type

### ISSUE THREAD

**Issue by Tomowok** [b13/masi#6]
Since [the last commit](https://github.com/b13/masi/commit/478c360136b1f85fc551c8ce62a083b1d00707cd), the field 'exclude_slug_for_subpages' does not appear anymore in pages for the "doktype" folder.

Thx.

**Comment by davidsteeb** [comment]
I prepared a fix:
https://github.com/b13/masi/pull/8

**Comment by Tomowok** [comment]
> I prepared a fix:
> #8

Nice !
Thx

**Comment by nostadt** [comment]
The PR has been merged. Is there a reason why this issue remains open?

**Comment by bmack** [comment]
Thanks, for closing the issue!
